import Header from "@/components/Header/Header";
import { ReduxProvider } from "@/redux/provider";

import "@/styles/globals.scss";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["400", "600"],
  subsets: ["latin-ext"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={poppins.style}>
        <ReduxProvider>
          <header>
            <Header />
          </header>
          <main className="container">{children}</main>
        </ReduxProvider>
      </body>
    </html>
  );
}
